### PR TITLE
Upgrade scalajs, scalajs-react and sbt

### PR DESCRIPTION
**Pull request by TimothyKlim**

### CODE REVIEW

**Comment by ochrons** [comment]
Are you seeing some issue with the current version that would require updating the dependencies?

**Comment by TimothyKlim** [comment]
Yes. I can't do fastopt with new scalajs react.

**Comment by TimothyKlim** [comment]
This is what I get with new scalajs-react: https://gist.github.com/TimothyKlim/2113fb67bce747776f6be61b01da4245

**Comment by ochrons** [comment]
Ok. so scalajs-react is not being backwards compatible in its patch version. I have some pending minor updates to Diode, so I could integrate these and publish a new version.

**Comment by TimothyKlim** [comment]
Ok, thanks!

**Pull request closed without merging**
